### ISSUE TITLE
/usr/bin/find: '/tmp': No such file or directory warning message

### ISSUE THREAD

**Issue by lzhang10** [otherguy/docker-dropbox#17] opened 2021-02-13 15:27 UTC
I just installed the latest version of the image and got this warning message every second in the log:

/usr/bin/find: '/tmp': No such file or directory

Everything else runs fine.

I vhecked and there is no /tmp directory in the image.

**Comment by otherguy** [comment] 2021-02-15 12:56
Hi @lzhang10 and thanks for your bug report! 

This was actually fixed in https://github.com/otherguy/docker-dropbox/issues/15. Could you please confirm you have the correct version of the image by providing the image digest you are using (paste the output of `docker inspect otherguy/dropbox:latest` here)?

**Comment by otherguy** [comment] 2021-02-15 13:42
I just updated the image (for an unrelated task). Now the latest version is `1.7.0` and the image digest should be `sha256:339984c002d1d5851a1cd145f274fe1e225773cc5ea5306efc5e56159c74b58f`. 

Can you please use this latest version and let me know if you still have the same issue?

**Comment by lzhang10** [comment] 2021-02-16 00:51
Previous image has the ID of dafee8a3f8d0, I did a pull and got 7a3515edb20a:

```
REPOSITORY         TAG       IMAGE ID       CREATED        SIZE
otherguy/dropbox   latest    7a3515edb20a   11 hours ago   1.06GB
otherguy/dropbox   <none>    dafee8a3f8d0   9 days ago     1.07GB
```

The tmp warning went away with the new image.

**Comment by otherguy** [comment] 2021-02-16 09:31
Oddly, [none of my published images](https://hub.docker.com/r/otherguy/dropbox/tags?page=1&ordering=last_updated) match this. Can you please do `docker image ls --digests otherguy/dropbox` to confirm the digests? I get `524e0cc66b3030ef368b00126327e6b17324297f58e48c9b13d8db78d97fa630` for this image but [this is not published on Dockerhub](https://hub.docker.com/layers/otherguy/dropbox/1.7.0/images/sha256-524e0cc66b3030ef368b00126327e6b17324297f58e48c9b13d8db78d97fa630?context=explore).

It's definitely not the previous [1.6.2](https://github.com/otherguy/docker-dropbox/releases/tag/1.6.2) release. No idea how you could have gotten that image.

Your latest image is correct and the digest matches the published [`1.7.0`](https://hub.docker.com/layers/otherguy/dropbox/1.7.0/images/sha256-339984c002d1d5851a1cd145f274fe1e225773cc5ea5306efc5e56159c74b58f?context=explore).

```bash
$ docker image ls --digests otherguy/dropbox
REPOSITORY         TAG       DIGEST                                                                    IMAGE ID       CREATED        SIZE
otherguy/dropbox   1.7.0     sha256:339984c002d1d5851a1cd145f274fe1e225773cc5ea5306efc5e56159c74b58f   7a3515edb20a   20 hours ago   1.06GB
otherguy/dropbox   1.6.2     sha256:f07bc6a101bbbddf6529ca22f9c25dcfc3a848b88f3707285125f0105e42ec52   843da554e49f   5 weeks ago    1.06GB
```

**Comment by lzhang10** [comment] 2021-02-17 17:06
The digests are:

```
$ docker image ls --digests otherguy/dropbox
REPOSITORY         TAG       DIGEST                                                                    IMAGE ID       CREATED       SIZE
otherguy/dropbox   latest    sha256:339984c002d1d5851a1cd145f274fe1e225773cc5ea5306efc5e56159c74b58f   7a3515edb20a   2 days ago    1.06GB
otherguy/dropbox   <none>    sha256:524e0cc66b3030ef368b00126327e6b17324297f58e48c9b13d8db78d97fa630   dafee8a3f8d0   10 days ago   1.07GB
```

I simply used docker pull otherguy/dropbox:latest the first time. However, since the last pull the latest digest matches yours.

Thanks!

**Comment by github0013** [comment] 2021-03-07 23:38
If I keep it running for a few days, I still get this 

<img width="758" alt="ubuntu_❐_0_●_3__tmux_" src="https://user-images.githubusercontent.com/809378/110259127-77dcd200-7fe9-11eb-8f82-9396b5ff55f5.png">

```
▶ uname -a
Linux ubuntu 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

▶ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

▶ docker -v
Docker version 20.10.3, build 48d30b5

▶ docker-compose -v
docker-compose version 1.28.4, build cabd5cfb
```

```
▶ docker image ls --digests otherguy/dropbox
REPOSITORY         TAG       DIGEST                                                                    IMAGE ID       CREATED      SIZE
otherguy/dropbox   latest    sha256:8d662fa1d741481a7c63704dc0f7dcc094f2d4d03788551ef3a8803b67fde1ff   049539a03e57   7 days ago   686MB
```

```
[
    {
        "Id": "sha256:049539a03e5703bdfed01d628ec31e8e1d4f1383771674f2cb6187b0e446a3bb",
        "RepoTags": [
            "otherguy/dropbox:latest"
        ],
        "RepoDigests": [
            "otherguy/dropbox@sha256:8d662fa1d741481a7c63704dc0f7dcc094f2d4d03788551ef3a8803b67fde1ff"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-02-28T13:53:34.267882161Z",
        "Container": "18167423d6c3cb84badf436336dd810a2cd69bb1e01fabfb79c136b77e119e1b",
        "ContainerConfig": {
            "Hostname": "18167423d6c3",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "17500/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "LC_ALL=C.UTF-8",
                "POLLING_INTERVAL=5"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/opt/dropbox/bin/dropboxd\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:2b3ab176236ece8ac08a90d969f3de9c7fbdd2f080e6a97ee116528481d29cef",
            "Volumes": {
                "/opt/dropbox/.dropbox": {},
                "/opt/dropbox/Dropbox": {}
            },
            "WorkingDir": "/opt/dropbox/Dropbox",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Alexander Graf <alex@otherguy.io>",
                "org.label-schema.build-date": "2021-02-28T13:52:27+00:00",
                "org.label-schema.description": "Standalone Dropbox client",
                "org.label-schema.name": "Dropbox",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "49f9852",
                "org.label-schema.vcs-url": "https://github.com/otherguy/docker-dropbox"
            }
        },
        "DockerVersion": "18.06.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "17500/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "LC_ALL=C.UTF-8",
                "POLLING_INTERVAL=5"
            ],
            "Cmd": [
                "/opt/dropbox/bin/dropboxd"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:2b3ab176236ece8ac08a90d969f3de9c7fbdd2f080e6a97ee116528481d29cef",
            "Volumes": {
                "/opt/dropbox/.dropbox": {},
                "/opt/dropbox/Dropbox": {}
            },
            "WorkingDir": "/opt/dropbox/Dropbox",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Alexander Graf <alex@otherguy.io>",
                "org.label-schema.build-date": "2021-02-28T13:52:27+00:00",
                "org.label-schema.description": "Standalone Dropbox client",
                "org.label-schema.name": "Dropbox",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "49f9852",
                "org.label-schema.vcs-url": "https://github.com/otherguy/docker-dropbox"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 686309749,
        "VirtualSize": 686309749,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/fac1a6bf5d95b82fada5dc297c30a9d7948571c92c02e67697677cc2338a9ce9/diff:/var/lib/docker/overlay2/2846363e9de0e1657f38aa83d8f8afa89db67a9874a1625c33614bdee4798c0b/diff:/var/lib/docker/overlay2/618ef5a43c3f6c23b94850bd56490a35b0ecddaef02eb8be0bdbc32209cdfc0c/diff:/var/lib/docker/overlay2/fdaf01c5bec97b0e738bdcdef360040372c06bf9a2945640882c23a7cd25d239/diff:/var/lib/docker/overlay2/f653e2572ed6f2247d3717d6aa42a2e7e67da1a942da27d5ccb8d9b859413f62/diff:/var/lib/docker/overlay2/de887ef536f6139b524953e1db5e4ceaf93a277bbf7b92e9fb4c2807db99d8bb/diff:/var/lib/docker/overlay2/da1b928b1583a1e2c6d5521aea324f380800e9d22a4d19ce0cb60b3269fa3d27/diff",
                "MergedDir": "/var/lib/docker/overlay2/93e7b6d6c773033e7e3b28bfcd27491c04a2eca5e340e2c23b02645b77a332a6/merged",
                "UpperDir": "/var/lib/docker/overlay2/93e7b6d6c773033e7e3b28bfcd27491c04a2eca5e340e2c23b02645b77a332a6/diff",
                "WorkDir": "/var/lib/docker/overlay2/93e7b6d6c773033e7e3b28bfcd27491c04a2eca5e340e2c23b02645b77a332a6/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:9eb82f04c782ef3f5ca25911e60d75e441ce0fe82e49f0dbf02c81a3161d1300",
                "sha256:a21efe83b85a3a0acc5ca8915be8769e1ac55bdfd4ad73406ac85a29cd28d13f",
                "sha256:9f26e745ed474b7e4c90d46b0da21e601070df783ff915727577bd53819d0afa",
                "sha256:0a84ef1f1118670fa27220e96fbe375e22ef708742d0ebe7eda7a7089e70614c",
                "sha256:b60b414f421d48862c4d345f273f2b0bb86158178c958560dadbc2c6db58657f",
                "sha256:c013ba63cdabd7ff44de39870b9151883e7945fdcb2aa3c4deb06f9acec6e64e",
                "sha256:5a2e3b5a06061db0965764f8e791f4df372b9e9cab246359fa34b262ad47af32",
                "sha256:94b6b2b73ba8ee7684948c9446a27d4f44dc62c634dab4153ab3e80a148bf05c"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by otherguy** [comment] 2021-03-08 13:10
@github0013 thanks for the (awesome) report!

I have just published [1.8.4](https://github.com/otherguy/docker-dropbox/releases/tag/1.8.4) with an attempted fix for that. Could you please try that one and report if the problem is going away?

**Comment by github0013** [comment] 2021-03-08 23:17
Thank you for a quick reply.
I just started running the latest, so let me get back to you in a few days.

**Comment by otherguy** [comment] 2021-03-08 23:18
Sure thing! I'll keep the ticket open until then.

**Comment by github0013** [comment] 2021-03-11 22:46
So it's been 3 days, and it still is working fine now.
I think this issue is resolved.  Thank you again!

```
▶ docker image ls --digests otherguy/dropbox
REPOSITORY         TAG       DIGEST                                                                    IMAGE ID       CREATED      SIZE
otherguy/dropbox   latest    sha256:d7257ec2b93113bc8a057b14c0011504e98165aec9d62dfbe04f2563a4d2d8b3   2f7319bfa6cb   3 days ago   697MB
```

**Comment by otherguy** [comment] 2021-03-12 09:44
Awesome :) I'm closing this then. Please create a new ticket if you still notice any issues!

**Closed by otherguy** 2021-03-12 09:44 UTC
Labels: bug, question
