### ISSUE TITLE
curl not installed

### ISSUE THREAD

**Issue by klara31** [otherguy/docker-dropbox#22] opened 2021-03-05 15:26 UTC
When starting the container, curl is used to check for a new version. However, curl is not installed!
```
# docker logs dropbox
Checking for latest Dropbox version...
/docker-entrypoint.sh: line 60: curl: command not found
Latest   :
Installed: 116.4.368
```

**Comment by otherguy** [comment] 2021-03-05 15:35
Thanks, that happened in the last release! Fixed in #23

**Closed** 2021-03-05 15:35 UTC
Labels: bug

**Comment by otherguy** [comment] 2021-03-05 16:25
@klara31 can you please try the `1.8.1` release and let me know if the issue is solved for you?

**Comment by klara31** [comment] 2021-03-05 16:31
```
# docker-compose up dropbox
Pulling dropbox (otherguy/dropbox:1.8.1)...
1.8.1: Pulling from otherguy/dropbox
45b42c59be33: Already exists
1b8dfacbd7fe: Pull complete
3ca2281c3d19: Pull complete
66e81259326b: Pull complete
d7077de14f5a: Pull complete
71d35d543af1: Pull complete
7112e949ce73: Pull complete
23efe28c9c70: Pull complete
Digest: sha256:c8e3c07b69eb0bb2fcd44c6d40a6728980873a5e0b47a03e03b44e1f471ddd5f
Status: Downloaded newer image for otherguy/dropbox:1.8.1
Recreating dropbox ... done
Attaching to dropbox
dropbox             | Checking for latest Dropbox version...
dropbox             | Latest   : 117.4.378
dropbox             | Installed: 117.4.378
dropbox             | Dropbox is up-to-date
```
looks to be running OK, thanks!

**Comment by otherguy** [comment] 2021-03-05 16:32
Great! Thanks for the bug report 😀
